### ISSUE TITLE
Cosh doesn't find standard library when installed to non-default prefix

### ISSUE THREAD

**Issue by KnorrFG** [tomhrr/cosh#51]
Hey, 
I installed cosh like this: `make prefix=/home/felix/.local install`, and when I now start cosh in a new terminal it says `unable to deserialise runtime library`

**Comment by tomhrr** [comment]
Thanks, this should be fine now (as at 5e97b1fd24768a3bda33552d5a71e088fb9039a8).

**Comment by KnorrFG** [comment]
Sorry, but that didnt fix it.
I ran cargo clean, make clean, make and make install again. Unless the current dir is the git repo, the error is still there.

**Comment by tomhrr** [comment]
Woops, sorry about that, it should actually be fixed this time.

**Comment by KnorrFG** [comment]
Nope, still does not work.
